name: Deploy The Pages :3c

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: queercoded-website
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

